### ISSUE TITLE
Doc claims that igc will modify kubectl, but it didn't (fix doc)

### ISSUE THREAD

**Issue by markstur** [cloud-native-toolkit/ibm-garage-developer-guide#309]
**Describe the bug**
Guide says:

As of v0.5.1, the IGC CLI will now install the commands as plugins to the kubectl and oc CLIs. For example, all of the following are equivalent...

But this doesn't seem to be true for kubectl.  Fine by me, but I think the docs should be fixed.

**To Reproduce**
1. npm i -g @ibmgaragecloud/cloud-native-toolkit-cli
2. kubectl pipeline
3. See usage error

**Expected behavior**
Since it shows `kubectl pipeline` is supposed to work, that's what I expect.
I'd rather it did not modify my kubectl anyway.  Just would like to trust the docs better.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
1. works for oc
2. if there is some kind of restart needed, it wasn't clear

**Comment by csantanapr** [comment]
Can't reproduce.

The CLI when install globally add the links/binary `kubectl-pipeline` to the PATH of node,  which both kubectl and oc read

To try it use `which`
```
which kubectl-pipeline
```
You will see it in the PATH
```
/Users/csantanapr/.nvm/versions/node/v16.1.0/bin/kubectl-pipeline
```
